roi:
  boundary: pokhran_rajasthan_india
start_year: 2016
end_year: 2026
dataset_version: pokhran_rajasthan_india_dynamic_world
tile_size_px: 512
season:
  start_month: 1
  end_month: 5
source: dynamic_world
endpoints_only: true
dataset: dynamic_world
