dataset:
  base_dir: ~/Documents/urdev
  name: data/urban_dataset_pokhran_rajasthan_india_dynamic_world
  pixel_resolution_m: 10
visualizations:
  years_to_mosaic:
  - 2016
  - 2026
  change_maps:
  - name: change_2016_2026
    year1: 2016
    year2: 2026
    target_class: 6
    highlight_color:
    - 255
    - 0
    - 128
    - 255
  palette:
  - '#419BDF'
  - '#397D49'
  - '#88B053'
  - '#7A87C6'
  - '#E49635'
  - '#DFC35A'
  - '#C4281B'
  - '#A59B8F'
  - '#B39FE1'
analysis:
  transition_pairs:
  - - 2016
    - 2026
regions:
  osmnx_place_query: Pokhran, Rajasthan, India
  admin_level: '10'
