dataset:
  base_dir: ~/Documents/urdev
  name: urban_dataset_singapore_vegetation
  pixel_resolution_m: 10
visualizations:
  years_to_mosaic:
  - 2020
  - 2021
  change_maps:
  - name: change_2020_2021
    year1: 2020
    year2: 2021
    target_class: 6
    highlight_color:
    - 255
    - 0
    - 128
    - 255
  palette:
  - '#419BDF'
  - '#397D49'
  - '#88B053'
  - '#7A87C6'
  - '#E49635'
  - '#DFC35A'
  - '#C4281B'
  - '#A59B8F'
  - '#B39FE1'
analysis:
  transition_pairs:
  - - 2020
    - 2021
regions:
  osmnx_place_query: Singapore
  admin_level: '10'
